<a href="https://colab.research.google.com/github/vanyaagarwal29/Python-Basics/blob/main/demo_004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Common ques
1. can we use lab? YES
2. Can we use Jupyter notebook locally? YES
3. Can we use neuro lab? YES
4. Can we use VSCODE? YES
4. Can we use PyCharm? YES
5. Can we use Colab? YES
6. Can we code simultaneosly code? YES definitely
7. Where are the resouces available? Its in you dashboard under the video that you play -
![image.png]()

9. Do we get notes? YES

# 30-45 mins. and 10-15 mins doubts

# AGENDA
0. Glimpse of conditional statements -
  - if-else condtions
1. Operators
  - Logical
  - Equality
  - Comparision
  - Arthimatic
  - Bitwise [Advance topics - covering in future classes]
  - Operators for sets and dictionary [Advance classes]

2. String methods
3. Control flow statement [if time permits]

## CONDITIONAL STATMENT (IF ELSE)

```python
if condition:
    print("execute this statement")
else:
    print("if condition is not True")
```

if its is raining then let's work from home else let's go to office

In [ ]:
raining = True

if raining: # TRUE CONDITION
    print("Lets do work from home") # This statemen exectuted
else:
    print("Lets go to office")

Lets do work from home

if its is raining then let's work from home else let's go to office

In [ ]:
raining = False # its not raining

if raining: # FALSE CONDITION
    print("Lets do work from home") #
else:
    print("Lets go to office") # This statemen exectuted

Lets go to office

### use of indentation

In [ ]:
raining = True

if raining: # TRUE CONDITION
print("Lets do work from home") # This statemen exectuted
else:
    print("Lets go to office")

IndentationError: ignored

In [ ]:
raining = True

if raining: # TRUE CONDITION
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted
else:
    print("Since its not raining...")
    print("Lets go to office")

Since its raining...
Lets do work from home

C language example code
```c
bool raining = True;

if raining{
    printf("Since its raining...");
    printf("Lets do work from home");
    }
```

if it's NOT raining then let's let's go to office ELSE let's work from home

In [ ]:
raining = True

if not raining: # False CONDITION
    print("Since its not raining...")
    print("Lets go to office")
else:
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted

Since its raining...
Lets do work from home

In [ ]:
raining = False

if not raining: # False CONDITION
    print("Since its not raining...")
    print("Lets go to office")
else:
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted

Since its not raining...
Lets go to office

In [ ]:
class_started = False

if class_started:
    print("Lets concentrate")
else:
    print("Lets revise previous class")

##  Logical opertors

Keywords | Meaning
- | -
not | unary negation
and | conditional AND
or | conditional OR

if class started then let's concentrate else revise the previous class

In [ ]:
class_started = True

if class_started:
    print("Since class started...")
    print("Lets concentrate")
else:
    print("Since class is not started...")
    print("let's revise")

Since class started...
Lets concentrate

In [ ]:
class_started = False

if class_started:
    print("Since class started...")
    print("Lets concentrate")
else:
    print("Since class is not started...")
    print("let's revise")

Since class is not started...
let's revise

if class NOT started then let's revise else let's concentrate class

In [ ]:
class_started = True

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

Since class started...
Lets concentrate

In [ ]:
class_started = False

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

Since class is not started...
let's revise

In [ ]:
# statements not alligned properly will give indentation error
class_started = False

if not class_started:
 print("Since class is not started...")
  print("let's revise")
else:
print("Since class started...")
    print("Lets concentrate")

IndentationError: ignored

In [ ]:
# statements not alligned properly will give indentation error
class_started = False

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

Since class is not started...
let's revise

In [ ]:
# # statements not alligned properly will give indentation error
# ## lets take it at the end:
# class_started = bool(input("Hey friend, is class started?: [0-False/1-True]"))

# if class_started:
#     print("Since class started...")
#     print("Lets concentrate")
# else:
#     print("Since class is not started...")
#     print("let's revise")

### and	 - conditional AND

Vegetable | Salt | Dish
- | - | -
False | False | False
False | True | False
True | False | False
True | True | True

In [ ]:
vegetable_present = False
salt_present = False

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

Its a bad dish
because vegetable present: False
and salt present: False

In [ ]:
vegetable_present = False
salt_present = True

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

Its a bad dish
because vegetable present: False
and salt present: True

In [ ]:
vegetable_present = True
salt_present = False

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

Its a bad dish
because vegetable present: True
and salt present: False

if vegetable and salt both are present in my dish then only my dish is good.

In [ ]:
vegetable_present = True
salt_present = True

if vegetable_present and salt_present: # this condition was true as both the sub conditions are true
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

Its a good dish

In [ ]:
name = "Satyam"
print(f"hi class my name is: {name}")

hi class my name is: Satyam

### or conditional OR

if I have a car or bike then I can travel 100kms in a day

Car | Bike | Travel_100_kms
- | - | -
False | False | False
False | True | True
True | False | True
True | True | True

In [ ]:
i_own_car = False
i_own_bike = False

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

I am stuck as I don't have car or bike!

In [ ]:
i_own_car = False
i_own_bike = True

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

I can travel 100 kms in a day!

In [ ]:
i_own_car = True
i_own_bike = False

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

I can travel 100 kms in a day!

In [ ]:
i_own_car = True
i_own_bike = True

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

I can travel 100 kms in a day!

## Conclusion -
1. use and operator when you want all the condition to be true
2. use or operator if anyone of the condition you want to be true

### example-

attendance | assignment | eligible_for_exam
- | - | -
>=75% | >=70% | True

In [ ]:
attendance = 70
assignment_submitted = 40

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendence criteria met? : False
assignment criteria met? : False
The student is not eligible

In [ ]:
attendance = 90
assignment_submitted = 40

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : False
The student is not eligible

In [ ]:
attendance = 90
assignment_submitted = 90

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : True
The student is eligible to appear in final exam


credit_card | debit_card | purchase_book_from_amazon
- | - | -
True | True | True
False | False | True

In [ ]:
own_credit_card = False
own_debit_card = False

if own_credit_card or own_debit_card:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

Ask from a dad for debit or credit card?
cash on delivery?

In [ ]:
own_credit_card = False
own_debit_card = True

if own_credit_card or own_debit_card:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

proceed further for payment

In [ ]:
own_credit_card = False
own_debit_card = False
Net_banking = True

if own_credit_card or own_debit_card or Net_banking:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

proceed further for payment

## and or together

attendance | assignment | sports_player | eligible_for_exam
- | - | - | -
>=75% | >=70% | False | True
>=75% | >=70% | True | True

In [ ]:
attendance = 70
assignment_submitted = 40
sports_player = True

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student is eligible to appear in final exam")
    else:
        print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendence criteria met? : False
assignment criteria met? : False
sports criteria met? : True
The student is not eligible

if attendence is more than 75% and assignment completed more than 70% OR the student is sports player then only the student is eligible for exam

if you are sports player then you will get grace marks = +10

In [ ]:
# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 75 # mendatory
sports_player = False # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student is can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : True
sports criteria met? : False
The student is eligible to appear in final exam but not extra grace marks

In [ ]:
# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 75 # mendatory
sports_player = True # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : True
sports criteria met? : True
The student can get grace marks = +10

In [ ]:
# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 40 # mendatory
sports_player = True # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : False
sports criteria met? : True
The student is not eligible

## Equality Operators

Operator | uses | Meaning
- | - | -
is | A is B=> | return True if A and B points to the same object
is not | A is not B | returns True if A and B do not points to the same object
== | A == B | A is equal to B
!= | A != B | A is not equal to B

When using `is` then we are also comparing memory location
When using `is not` then we are also comparing memory location

== and != is only checking value of the variables [Used more offently or frequently]

In [ ]:
A = 1
B = 1

if A is B:
    print("A and B are same")
else:
    print("A and B are not same")

A and B are same

In [ ]:
id(A)

11122592

In [ ]:
id(B)

11122592

In [ ]:
A = 1
B = 2

if A is B:
    print("A and B are same")
else:
    print("A and B are not same")

A and B are not same

In [ ]:
A = 1
B = 2

if A is not B:
    print("A and B are not same")
else:
    print("A and B are same")

A and B are not same

In [ ]:
A = 1
B = 1

if A == B: # A and B are having same value
    print("A and B are same")
else:
    print("A and B are not same")

A and B are same

In [ ]:
A = 1
B = 2

if A != B:
    print("A and B are not same")
else:
    print("A and B are same")

A and B are not same

In [ ]:
A = "Sunny"
B = "Sunny"

A is B

True

In [ ]:
A = ["Sunny", "Rishav"]  # list data structure # array in other language
B = ["Sunny", "Rishav"]  # list data structure

A is B

False

In [ ]:
A == B

True

In [ ]:
A is not B

True

In [ ]:
id(A)

140261839205312

In [ ]:
id(B)

140261838852176

In [ ]:
A = int(input("Enter the value of A: "))
B = int(input("Enter the value of B: "))

A is B

Enter the value of A: 1
Enter the value of B: 1

True

In [ ]:
A = 1
B = int(input("Enter the value of B: "))

A is B

Enter the value of B: 1

True

In [ ]:
name = input("Enter your name: ")

if name == "Sunny Bhaveen Chandra":
    print(f"He is the mentor")
else:
    print(f"Its possible that he/she is a student")

Enter your name: Sunny Bhaveen Chandra
He is the mentor

In [ ]:
name = input("Enter your name: ")

if name == "Sunny Bhaveen Chandra":
    print(f"He is the mentor")
else:
    print(f"Its possible that he/she is a student")

Enter your name: Satyam
Its possible that he/she is a student

In [ ]:
name = input("Enter your name: ")

if name == "Sunny Bhaveen Chandra":
    print("He is the mentor")
else:
    print("Its possible that he/she is a student")

Enter your name: Sunny Chandra
Its possible that he/she is a student

In [ ]:
name = input("Enter your name: ")

if name == "Sunny Bhaveen Chandra":
    print(f"He is the mentor")
else:
    print(f"Its possible that he/she is a student")

Enter your name: sunny bhaveen chandra
Its possible that he/she is a student

### Comparision

Operation | Meaning
- | -
< | A < B
<= | A <= B
> | A > B
>= | A >= B

In [ ]:
attendance = 75
assignment_submitted = 70

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendence criteria met? : True
assignment criteria met? : True
The student is eligible to appear in final exam

In [ ]:
your_score = 40
passing_marks = 33.33

if your_score >= 33.33:
    print(f"Since you have scored: {your_score}, you have passed the exams!")
else:
    print("Dad: You should have taken things seriously!")

Since you have scored: 40, you have passed the exams!

In [ ]:
your_score = 30
passing_marks = 33.33

if your_score >= 33.33:
    print(f"Since you have scored: {your_score}, you have passed the exams!")
else:
    print("Dad: You should have taken things seriously!")

Dad: You should have taken things seriously!

In [ ]:
your_score = 33.33
passing_marks = 33.33

if your_score > 33.33: # strict case
    print(f"Since you have scored: {your_score}, you have passed the exams!")
else:
    print("Dad: You should have taken things seriously!")

Dad: You should have taken things seriously!

In [ ]:
your_score = 33.33
passing_marks = 33.33
distinction_marks = 75

if your_score >= 33.33: # strict case
    print(f"Since you have scored: {your_score}, you have passed the exams!")
    if your_score > distinction_marks:
        print("Dad: I will buy you a bike! Well Done!!")
else:
    print("Dad: You should have taken things seriously!")

Since you have scored: 33.33, you have passed the exams!

In [ ]:
your_score = 90
passing_marks = 33.33
distinction_marks = 75

if your_score > 33.33: # strict case
    print(f"Since you have scored: {your_score}, you have passed the exams!")
    if your_score > distinction_marks:
        print("Dad: I will buy you a bike! Well Done!!")
else:
    print("Dad: You should have taken things seriously!")

Since you have scored: 90, you have passed the exams!
Dad: I will buy you a bike! Well Done!!

In [ ]:
your_score = 60
passing_marks = 33.33
distinction_marks = 75

if your_score > 33.33: # strict case
    print(f"Since you have scored: {your_score}, you have passed the exams!")
    if your_score > distinction_marks:
        print("Dad: I will buy you a bike! Well Done!!")
    else:
        print("Dad: Better luck next time!")
else:
    print("Dad: You should have taken things seriously!")

Since you have scored: 60, you have passed the exams!
Dad: Better luck next time!