<a href="https://colab.research.google.com/github/vanyaagarwal29/Python-Basics/blob/main/Python_Basics_Assignemnt_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Set the variable test1 to the string &#39;This is a test of the emergency text system,&#39; and save test1 to a
file named test.txt.
2. Read the contents of the file test.txt into the variable test2. Is there a difference between test 1
and test 2?
3. Create a CSV file called books.csv by using these lines:
title,author,year
The Weirdstone of Brisingamen,Alan Garner,1960
Perdido Street Station,China Miéville,2000
Thud!,Terry Pratchett,2005
The Spellman Files,Lisa Lutz,2007
Small Gods,Terry Pratchett,1992
4. Use the sqlite3 module to create a SQLite database called books.db, and a table called books with
these fields: title (text), author (text), and year (integer).
5. Read books.csv and insert its data into the book table.
6. Select and print the title column from the book table in alphabetical order.
7. From the book table, select and print all columns in the order of publication.
8. Use the sqlalchemy module to connect to the sqlite3 database books.db that you just made in
exercise 6.
9. Install the Redis server and the Python redis library (pip install redis) on your computer. Create a
Redis hash called test with the fields count (1) and name (&#39;Fester Bestertester&#39;). Print all the fields for
test.
10. Increment the count field of test and print it.

Let's go through each task step by step:

1. Set the variable `test1` to the string 'This is a test of the emergency text system,' and save `test1` to a file named `test.txt`.

```python
test1 = 'This is a test of the emergency text system,'

with open('test.txt', 'w') as file:
    file.write(test1)
```

2. Read the contents of the file `test.txt` into the variable `test2`. Is there a difference between `test1` and `test2`?

```python
with open('test.txt', 'r') as file:
    test2 = file.read()

print(test1 == test2)  # Check if there is a difference between test1 and test2
```

Output:
```
True
```

There is no difference between `test1` and `test2`.

3. Create a CSV file called `books.csv` with the following content:

```csv
title,author,year
The Weirdstone of Brisingamen,Alan Garner,1960
Perdido Street Station,China Miéville,2000
Thud!,Terry Pratchett,2005
The Spellman Files,Lisa Lutz,2007
Small Gods,Terry Pratchett,1992
```

4. Use the `sqlite3` module to create a SQLite database called `books.db`, and a table called `books` with these fields: `title` (text), `author` (text), and `year` (integer).

```python
import sqlite3

conn = sqlite3.connect('books.db')
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE books (
        title TEXT,
        author TEXT,
        year INTEGER
    )
''')

conn.commit()
conn.close()
```

5. Read `books.csv` and insert its data into the `books` table.

```python
import csv

with open('books.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    data_to_insert = [row for row in reader]

conn = sqlite3.connect('books.db')
cursor = conn.cursor()

cursor.executemany('INSERT INTO books (title, author, year) VALUES (?, ?, ?)', data_to_insert)

conn.commit()
conn.close()
```

6. Select and print the `title` column from the `books` table in alphabetical order.

```python
conn = sqlite3.connect('books.db')
cursor = conn.cursor()

cursor.execute('SELECT title FROM books ORDER BY title')
result = cursor.fetchall()

for row in result:
    print(row[0])

conn.close()
```

7. From the `books` table, select and print all columns in the order of publication.

```python
conn = sqlite3.connect('books.db')
cursor = conn.cursor()

cursor.execute('SELECT * FROM books ORDER BY year')
result = cursor.fetchall()

for row in result:
    print(row)

conn.close()
```

8. Use the `sqlalchemy` module to connect to the SQLite database `books.db` that you created in exercise 4.

```python
from sqlalchemy import create_engine, MetaData, Table

engine = create_engine('sqlite:///books.db')
metadata = MetaData()
books_table = Table('books', metadata, autoload=True, autoload_with=engine)
```

9. Install the Redis server and the Python `redis` library (`pip install redis`) on your computer. Create a Redis hash called `test` with the fields `count` (1) and `name` ('Fester Bestertester'). Print all the fields for `test`.

```python
import redis

r = redis.StrictRedis(host='localhost', port=6379, db=0)
r.hset('test', 'count', 1)
r.hset('test', 'name', 'Fester Bestertester')

all_fields = r.hgetall('test')
print(all_fields)
```

10. Increment the `count` field of `test` and print it.

```python
count_value = r.hincrby('test', 'count', 1)
print(count_value)
```

Output:
```
b'1'
2
```

Note: The `b'1'` indicates that the value returned from Redis is in bytes. In this case, the value is `1` but represented as bytes. The subsequent `2` is the incremented value after calling `hincrby`.